package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"
	"errors"

	accountclient "github.com/r7rainz/go-grpc-graphql/account/client"
)

// Orders is the resolver for the orders field.
func (r *accountResolver) Orders(ctx context.Context, obj *Account) ([]*Order, error) {
	return []*Order{}, nil
}

// CreateAccount is the resolver for the createAccount field.
func (r *mutationResolver) CreateAccount(ctx context.Context, account AccountInput) (*Account, error) {
	createdAccount, err := r.accountClient.PostAccount(ctx, account.Name)
	if err != nil {
		return nil, err
	}

	return accountFromClient(createdAccount), nil
}

// CreateProduct is the resolver for the createProduct field.
func (r *mutationResolver) CreateProduct(ctx context.Context, product ProductInput) (*Product, error) {
	return nil, errors.New("create product resolver not implemented")
}

// CreateOrder is the resolver for the createOrder field.
func (r *mutationResolver) CreateOrder(ctx context.Context, order OrderInput) (*Order, error) {
	return nil, errors.New("create order resolver not implemented")
}

// Accounts is the resolver for the accounts field.
func (r *queryResolver) Accounts(ctx context.Context, pagination *PaginationInput, id *string) ([]*Account, error) {
	if id != nil {
		account, err := r.accountClient.GetAccount(ctx, *id)
		if err != nil {
			return nil, err
		}
		if account == nil {
			return []*Account{}, nil
		}

		return []*Account{accountFromClient(account)}, nil
	}

	skip, take := 0, 0
	if pagination != nil {
		if pagination.Skip != nil {
			skip = *pagination.Skip
		}
		if pagination.Take != nil {
			take = *pagination.Take
		}
	}

	accounts, err := r.accountClient.GetAccounts(ctx, skip, take)
	if err != nil {
		return nil, err
	}

	graphAccounts := make([]*Account, 0, len(accounts))
	for _, account := range accounts {
		graphAccount := accountFromClient(account)
		if graphAccount != nil {
			graphAccounts = append(graphAccounts, graphAccount)
		}
	}

	return graphAccounts, nil
}

// Products is the resolver for the products field.
func (r *queryResolver) Products(ctx context.Context, pagination *PaginationInput, query *string, id *string) ([]*Product, error) {
	return nil, errors.New("products resolver not implemented")
}

// Account returns AccountResolver implementation.
func (r *Resolver) Account() AccountResolver { return &accountResolver{r} }

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type (
	accountResolver  struct{ *Resolver }
	mutationResolver struct{ *Resolver }
	queryResolver    struct{ *Resolver }
)

func accountFromClient(account *accountclient.Account) *Account {
	if account == nil {
		return nil
	}

	return &Account{
		ID:     account.ID,
		Name:   account.Name,
		Orders: []Order{},
	}
}
